### ISSUE TITLE
Can not build with the new Go version

### ISSUE THREAD

**Issue by EdenSpire** [mholt/caddy-webdav#42]
Hello,

I can not build / install the Webdav plugin for Docker.
I've tried numerous times.

I've tried to update my GO version with this tutorial:
`https://go.dev/doc/install`

This is the error message:
`18.94 go: github.com/mholt/caddy-webdav@v0.0.0-20240520160950-4ed1c0733370 requires go >= 1.22.0 (running go 1.21.10; GOTOOLCHAIN=local)
18.94 2024/05/22 02:58:06 [FATAL] exit status 1`

go version:
`go version go1.22.3 linux/amd64`

Please help.

**Comment by francislavoie** [comment]
> requires go >= 1.22.0 (running go 1.21.10; GOTOOLCHAIN=local)

Obviously you're not running the Go version you think you are. If you actually use 1.22.3 to build, it'll work fine. I'm not sure what you did wrong without seeing more context of your setup.

That said, this is happening because of a bad dependency update in this repo (requiring a higher Caddy version than v2.7.6 was requiring), and #43 will resolve it.
