### ISSUE TITLE
Auth only for Webdav

### ISSUE THREAD

**Issue by prakis** [mholt/caddy-webdav#50]
Hi,

My requirment is to upload files to caddyserver using webdav.

I am able to build caddy with webdav and configured with basicauth. I am able to upload files succesfully, but now when I visit the site, it is asking for authentication. I only want auth for webdav, not for general site visitors.

My Caddyfile config

{
    order webdav before file_server
}

mywebsite.com {
    root * /path/www
   webdav  {
       basicauth {
           users { 
               myusername = "pass"
           }
       }
     file_server browse
   }

}

Thank you.

**Comment by mholt** [comment]
Use matchers on the `basicauth` directive: https://caddyserver.com/docs/caddyfile/matchers (which is now `basic_auth` btw)

If you have webdav only for a certain path, use a path matcher. If you only want to authenticate webdav uploads, you can use a method matcher. Etc.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your questions.
